image: aminerachyd/projet-conteneurs-partie6

stages:
  - test
  - deploy
services:
  - name: mysql:latest
    alias: mysql-container-p5
    command: ["--default-authentication-plugin=mysql_native_password"]
variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - touch test.jpg
    - npm install
    - npm install -g mocha
    - npm run test

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker login --username_ --password=$HEROKU_API_KEY registry.heroky.com
    - docker pull aminerachyd/projet-conteneurs-partie6
    - docker tag aminerachyd/projet-conteneurs-partie6 registry.heroku.com/projet-conteneurs-partie7/web
    - docker push registry.heroku.com/projet-conteneurs-partie7/web
    - docker run -rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app projet-conteneurs-partie7
# deploy:
#   image: ruby:latest
#   stage: deploy
#   script:
#     # Installer heroku
#     # se connecter a heroku
#     # login heroku and deploy app with heroku push:web --app
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
