image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: db
    MYSQL_ROOT_PASSWORD: root
  script:
    - npm install -g mocha
    - npm run test
    - node index
