image: aminerachyd/projet-conteneurs-partie6

stages:
  - test
  - deploy
services:
  - name: mysql:latest
    alias: mysql-container-p5
    command: ["--default-authentication-plugin=mysql_native_password"]
variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - touch test.jpg
    - npm install
    - npm install -g mocha
    - npm run test

deploy:
  image: ruby:latest
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
