image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

services:
  - mysql:latest
  - docker:dind

variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - docker info
