image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - node install
    - node install -g mocha
    - node index
