image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

services:
  - mysql:latest
  - docker:dind

variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  image: tmaier/docker-compose:latest
  script:
    - npm install
    - npm install -g mocha
    - npm run test
    # - curl -L --fail https://github.com/docker/compose/releases/download/1.27.4/run.sh -o /usr/local/bin/docker-compose
    # - chmod +x /usr/local/bin/docker-compose
    - docker-compose up
    # - node index
