image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

services:
  - name: mysql:latest
    command: ["--default-authentication-plugin=mysql_native_password"]
variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - touch test.jpg
    - npm install
    - npm install -g mocha
    - npm run test
