image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

services:
  - mysql:latest
  - docker:dind

variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root

test:
  stage: test
  script:
    - npm install
    - npm install -g mocha
    - npm run test
    - apt update
    # Install docker
    # - apt install docker.io -y
    - apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
    - apt-get update
    - apt-get install docker-ce
    # Install docker-compose
    - curl -L --fail https://github.com/docker/compose/releases/download/1.27.4/run.sh -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose up
