image: aminerachyd/projet-conteneurs-partie6

stages:
  # - test TODO uncomment this
  - deploy
services:
  - name: mysql:latest
    alias: mysql-container-p5
    command: ["--default-authentication-plugin=mysql_native_password"]
variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: root
  DOCKER_DRIVER: overlay
  HEROKU_APP_NAME: projet-conteneurs-partie7
  HEROKU_AUTH_TOKEN: ${HEROKU_AUTH_TOKEN}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web

# test:
#   stage: test
#   script:
#     - touch test.jpg
#     - npm install
#     - npm install -g mocha
#     - npm run test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker build -t aminerachyd/projet-conteneurs-partie6 .
    - docker tag aminerachyd/projet-conteneurs-partie6 $HEROKU_REGISTRY_IMAGE
    - docker push $HEROKU_REGISTRY_IMAGE
    # Deployer sur heroku avec cette commande
    # Pas de heroku dans le container dind
    # - heroku container:release web --app $HEROKU_APP_NAME

    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_AUTH_TOKEN
