image: aminerachyd/projet-conteneurs-partie6

stages:
  - test

test:
  stage: test
  script:
    - apk add --update py-pip && pip install docker-compose
    - npm install -g mocha
    - docker-compose up
