version: "3"
services:
  app:
    build: .
    container_name: app-container-p5
    volumes:
      - ./public/img:/usr/src/app/public/img
    ports:
      - "8080:5000"
    networks:
      - network-p5
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql-container-p5
    command: --init-file /data/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/data/init.sql
    ports:
      - "3306:3306"
    networks:
      - network-p5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8070:80"
    networks:
      - network-p5
    environment:
      PMA_HOST: mysql

networks:
  network-p5:
    driver: bridge
